[workspace]
authors = ["Ashwin Prasanth Hariharan <ashwinprasanth06@gmail.com>"]
channels = ["conda-forge"]
name = "HS202_repo"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.11,<3.13"
pip = ">=23"

# Core
numpy = ">=1.26,<2.1"
scipy = ">=1.11,<1.13"
matplotlib = ">=3.8,<3.9"
opencv = "*"

# Jupyter stack
ipykernel = "*"
notebook = "*"
